-- MySQL Script generated by MySQL Workbench
-- Sat Oct 28 11:58:31 2017
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tradeFree
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tradeFree` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `tradeFree` ;

-- -----------------------------------------------------
-- Table `tradeFree`.`instrument`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tradeFree`.`instrument` ;

CREATE TABLE IF NOT EXISTS `tradeFree`.`instrument` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `externalName` VARCHAR(12) NOT NULL,
  `ISIN` VARCHAR(12) NULL,
  `fullName` VARCHAR(128) NULL,
  `deleted` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tradeFree`.`yahooRawPrice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tradeFree`.`yahooRawPrice` ;

CREATE TABLE IF NOT EXISTS `tradeFree`.`yahooRawPrice` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `open` DOUBLE NULL,
  `close` VARCHAR(45) NULL,
  `high` VARCHAR(45) NULL,
  `low` VARCHAR(45) NULL,
  `date` DATE NOT NULL,
  `instrumentId` BIGINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `dailyData` (`date` ASC),
  INDEX `yahooInstrumentId_idx` (`instrumentId` ASC),
  CONSTRAINT `yahooInstrumentId`
    FOREIGN KEY (`instrumentId`)
    REFERENCES `tradeFree`.`instrument` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tradeFree`.`derivedMetrics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tradeFree`.`derivedMetrics` ;

CREATE TABLE IF NOT EXISTS `tradeFree`.`derivedMetrics` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `dailyReturn` DOUBLE NULL,
  `volatility` DOUBLE NULL,
  `trend` INT NULL,
  `instrumentId` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `instrumentId_idx` (`instrumentId` ASC),
  CONSTRAINT `derivedInstrumentId`
    FOREIGN KEY (`instrumentId`)
    REFERENCES `tradeFree`.`instrument` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tradeFree`.`ecbFxRate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tradeFree`.`ecbFxRate` ;

CREATE TABLE IF NOT EXISTS `tradeFree`.`ecbFxRate` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `currencyPair` VARCHAR(45) NOT NULL,
  `baseCurrency` VARCHAR(45) NULL,
  `quoteCurrency` VARCHAR(45) NULL,
  `rate` DECIMAL(10,4) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `dailyData` (`date` ASC, `rate` ASC, `currencyPair` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tradeFree`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tradeFree`.`transaction` ;

CREATE TABLE IF NOT EXISTS `tradeFree`.`transaction` (
  `id` BIGINT NOT NULL,
  `date` DATE NULL,
  `side` VARCHAR(4) NOT NULL,
  `avgPx` DECIMAL(8,4) NOT NULL,
  `quantity` INT NOT NULL,
  `instrumentId` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `instrumentId_idx` (`instrumentId` ASC),
  CONSTRAINT `transactioInstrumentId`
    FOREIGN KEY (`instrumentId`)
    REFERENCES `tradeFree`.`instrument` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tradeFree`.`position`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tradeFree`.`position` ;

CREATE TABLE IF NOT EXISTS `tradeFree`.`position` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `instrumentId` BIGINT NOT NULL,
  `quantity` INT NOT NULL,
  `value` DECIMAL(10,2) NULL,
  `currency` VARCHAR(3) NOT NULL DEFAULT 'SEK',
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`instrumentId` ASC),
  CONSTRAINT `positionInstrumentId`
    FOREIGN KEY (`instrumentId`)
    REFERENCES `tradeFree`.`instrument` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
